# Generated by Django 2.0 on 2018-10-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20180920_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='contributor',
            field=models.CharField(blank=True, help_text='An entity responsible for making contributions to the content of the resource.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='coverage',
            field=models.CharField(blank=True, help_text='Coverage will typically include spatial location (a place name or geographic coordinates), temporal period (a period label, date, or date range) or jurisdiction (such as a named administrative entity).', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='format',
            field=models.CharField(blank=True, help_text='Format may include the media-type or dimensions of the resource.', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='relation',
            field=models.CharField(blank=True, help_text='A reference to a related resource.', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='rights',
            field=models.CharField(blank=True, help_text='A Rights element will contain a rights management statement for the resource, or reference a service providing such information.', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='source',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(blank=True, help_text='Genre', max_length=60, null=True),
        ),
    ]
