# Generated by Django 2.0 on 2018-10-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20181019_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='born_in',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='education',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
