# Generated by Django 2.0 on 2018-10-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20181024_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='awards',
            field=models.TextField(blank=True, null=True),
        ),
    ]
