# Generated by Django 2.0 on 2018-10-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_author_awards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='awards',
            field=models.CharField(blank=True, choices=[('booker', 'Booker Award'), ('caldecott', 'Caldecott Medal'), ('nba', 'National Book Award'), ('nbcca', 'National Book Critics Circle Award'), ('newbery', 'Newbery Medal'), ('npl', 'Nobel Prize for Literature'), ('p/f', 'PEN/Faulkner Award'), ('pp', 'Pulitzer Prize'), ('cwp', "Commonwealth Writers' Prize"), ('emma', 'EMMA Awards')], max_length=10, null=True),
        ),
    ]
